# Generated by Django 5.2.3 on 2025-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_job_company_remove_review_reviewed_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerequest',
            name='learn_skill',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='teach_skill',
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
