# Generated by Django 5.2.3 on 2025-10-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_skillprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
