# Generated by Django 5.2.3 on 2025-10-31 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_exchangerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillprofile',
            name='learn_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillprofile',
            name='teach_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
