# Generated by Django 5.2.3 on 2025-11-01 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_exchangerequest_status_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Chat',
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
