# Generated by Django 5.2.3 on 2025-11-02 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_job_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hr_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
